{"name": "test_verify_phone_no[device2-phone_number1]", "status": "passed", "attachments": [{"name": "log", "source": "b52e0a86-593c-48f8-b75b-ea92a38514cd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "appium_driver", "value": "'device2'"}, {"name": "phone_number", "value": "['1234']"}], "start": 1638782777744, "stop": 1638782786306, "uuid": "01be627e-2dbd-4493-9a33-fc88e9d6a175", "historyId": "94ba9546c8df23236afa1f0692ab1c51", "testCaseId": "8f179043caacb0abcb24fe30a00081a0", "fullName": "test_cases.test_verify_ph_no.TestVerifyPhoneNo#test_verify_phone_no", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log_on_failure', 'appium_driver')"}, {"name": "tag", "value": "flaky(reruns=3)"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_verify_ph_no"}, {"name": "subSuite", "value": "TestVerifyPhoneNo"}, {"name": "host", "value": "EPINHYDW042A"}, {"name": "thread", "value": "24716-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_verify_ph_no"}]}