{"uuid": "1d8a7a51-33bc-4185-8c02-190a995e385d", "children": ["c8428176-df72-40f1-af6e-3c33347d7b21"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1638784653464, "stop": 1638784653464}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\n    at UIA2Proxy.command (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:274:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)\n", "trace": "  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Python_Demo\\test_cases\\conftest.py\", line 55, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name=\"screenshot\", attachment_type=AttachmentType.PNG)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1353, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1365, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"C:\\Users\\Animesh_Mukherjee\\PycharmProjects\\Appium_Page_Object_Model\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1638784655445, "stop": 1638784655457}], "start": 1638784653464, "stop": 1638784655457}